### ISSUE TITLE
Plugin can't render verbatim

### ISSUE THREAD

**Issue by rajkaran** [sullinger/grunt-twig-render#7]
Hi there,

I am using angularjs with symfony, I need to use {%verbatim%} in my twig template in order to prevent angularjs variables getting render by twig. 

When I tries to render twig template with this grunt plugin I gets the below error:

    $ grunt twigRender
    Running "twigRender:eclipse" (twigRender) task
    Error compiling twig template app/templates/Default/summary.html.twig:
    TwigException: Unable to parse 'verbatim'
    Error parsing twig template app/templates/Default/summary.html.twig:
    TypeError: Cannot read property 'forEach' of undefined
    at Object.Twig.forEach (C:\xampp\htdocs\eclipse\web\bundles\insighteclipse\node_modules\grunt-twig-render\node_modules\twig\twig.min.js:8:821) 
    at Twig.parse C:\xampp\htdocs\eclipse\web\bundles\insighteclipse\node_modules\grunt-twig-render\node_modules\twig\twig.min.js:8:7061)
    at Twig.Template.render (C:\xampp\htdocs\eclipse\web\bundles\insighteclipse\node_modules\grunt-twig-render\node_modules\twig\twig.min.js:8:11602)
    at GruntTwigRender.render (C:\xampp\htdocs\eclipse\web\bundles\insighteclipse\node_modules\grunt-twig-render\tasks\twigRender.js:108:45)
    at C:\xampp\htdocs\eclipse\web\bundles\insighteclipse\node_modules\grunt-twig-render\tasks\twigRender.js:191:16
    at Array.forEach (native)
    at Object.<anonymous> (C:\xampp\htdocs\eclipse\web\bundles\insighteclipse\node_modules\grunt-twig-render\tasks\twigRender.js:181:16)
    at Object.<anonymous> (C:\xampp\htdocs\eclipse\web\bundles\insighteclipse\node_modules\grunt\lib\grunt\task.js:264:15)
    at Object.thisTask.fn (C:\xampp\htdocs\eclipse\web\bundles\insighteclipse\node_modules\grunt\lib\grunt\task.js:82:16)
    at Object.<anonymous> (C:\xampp\htdocs\eclipse\web\bundles\insighteclipse\node_modules\grunt\lib\util\task.js:301:30)
    File app/html/Default/summary.html created.
    File app/html/Sample/sample.html created.

Below is the code I am using to to render twig template:

	twigRender: {
		eclipse: {
			files : [
				{
					data: { 
						greeting: "Hello",
						target: "world"
					}, 
					expand: true,
					cwd: '<%= yeoman.app %>/templates',
					src: ['**/*.twig', '!**/_*.twig'], // Match twig templates but not partials
					dest: '<%= yeoman.app %>/html',
					ext: '.html' 
				}
			],
			options:{
				extensions:[
					function(Twig){
						Twig.exports.extendFunction( "asset", function( source ){
							return source.split('insighteclipse/')[1];
						});
						Twig.exports.extendFunction( "path", function( source ){
							return source;
						});
					}
				]
			}
		},
	},

Below is the part of template where I am using {% verbatim %}

	<section class="col-sm-9">
		<article class="thumbnail" id="content">
			<div class="alert alert-info  text-center" id="unit">WH-2500</div>
			<div class="table-responsive" id="overview"></div>
			<div class="" id="detail" data-ng-controller="censusCtrl">
				<table class="table table-stripped">
					<thead>
						<tr>
							<th data-ng-repeat = "(key,value) in fields">{% verbatim %}{{key}}{% endverbatim %}</th>
						</tr>
					</thead>
					<tbody>
						<tr data-ng-repeat = "record in records">
							<td data-ng-repeat = "(key,value) in record">{% verbatim %}{{value}}{% endverbatim %}</td>
						</tr>
					</tbody>
				</table>
			</div>
		</article>
	</section>

Any help

Raj

Update:

I have found the work around by reading this post - http://stackoverflow.com/questions/10834390/angularjs-on-a-symfony2-application

But I would like to use {% verbatim %}, so can we have support for this?

**Comment by sullinger** [comment]
Hi Raj,

is it possible that you use the [raw tag](https://github.com/justjohn/twig.js/pull/69) instead? The problem is that the verbatim tag has not yet been implemented – although [there is an open pull request in twig.js](https://github.com/justjohn/twig.js/pull/185). Please remember that my plugin is just a wrapper around Twig.js and therefore depends on its implementations of the Twig language.

So instead of `{% verbatim %}{{key}}{% endverbatim %}` you could just use `{% raw %}{{key}}{% endraw %}`

You can also try to add a custom tag yourself. Have a look at Example 3 [on my readme page](https://github.com/sullinger/grunt-twig-render#optionsextensions).


Stefan

**Comment by rajkaran** [comment]
Thank you stefan,

I am using {% verbatim %} but,  I have created the functions based on the example you have pointed to.

Raj
